# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Ecolec' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 4.7'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
end
